version: '3'

services:
  postgres:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dictionary
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker:/home/docker
    ports:
      - "5432:5432"

volumes:
  postgres-data:
